AllCops:
  TargetRubyVersion: 2.0
  DisplayCopNames: true
  Exclude:
    - spec/dummy/db/schema.rb

Style/Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - lib/active_record/events/extension.rb

Metrics/AbcSize:
  Exclude:
    - lib/active_record/events/extension.rb

Metrics/MethodLength:
  Exclude:
    - lib/active_record/events/extension.rb

Metrics/BlockLength:
  ExcludedMethods:
    - describe
