AllCops:
  TargetRubyVersion: 2.0
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
    - spec/dummy/db/schema.rb
    - tmp/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 80

Naming/PredicateName:
  Exclude:
    - lib/active_record/events/extension.rb

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context

Style/StringLiterals:
  Exclude:
    - gemfiles/*.gemfile

Style/MixinUsage:
  Exclude:
    - Rakefile
