language: ruby

rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - 2.3.8
  - 2.2.10
  - 2.1.10
  - 2.0.0

gemfile:
  - gemfiles/activerecord_6.0.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.0.gemfile

before_script:
  - bundle exec rake db:migrate

script:
  - bundle exec rspec
  - bundle exec rubocop
