language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.2

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.2.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_3.2.gemfile

before_script:
  - bundle exec rake db:migrate

script:
  - bundle exec rspec
  - bundle exec rubocop
