language: ruby

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

matrix:
  exclude:
    - rvm: 1.9
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/5.0.gemfile

before_script:
  - bundle exec rake db:migrate
