language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/5.0.gemfile

before_script:
  - bundle exec rake db:migrate
